/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as eventManagerSol from "./EventManager.sol";
export type { eventManagerSol };
export type { POAP } from "./POAP";
