/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface EventManagerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "attended"
      | "certificates"
      | "confirmAttendance"
      | "eventMetadataURI"
      | "getCertificate"
      | "owner"
      | "poap"
      | "renounceOwnership"
      | "setEventMetadataURI"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AttendanceConfirmed"
      | "EventMetadataUpdated"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "attended",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "certificates",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "confirmAttendance",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "eventMetadataURI",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCertificate",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "poap", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setEventMetadataURI",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "attended", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "certificates",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confirmAttendance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "eventMetadataURI",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCertificate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "poap", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setEventMetadataURI",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace AttendanceConfirmedEvent {
  export type InputTuple = [
    attendee: AddressLike,
    ens: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [attendee: string, ens: string, timestamp: bigint];
  export interface OutputObject {
    attendee: string;
    ens: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EventMetadataUpdatedEvent {
  export type InputTuple = [newURI: string];
  export type OutputTuple = [newURI: string];
  export interface OutputObject {
    newURI: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EventManager extends BaseContract {
  connect(runner?: ContractRunner | null): EventManager;
  waitForDeployment(): Promise<this>;

  interface: EventManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  attended: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  certificates: TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, string] & {
        eventId: bigint;
        timestamp: bigint;
        ens: string;
      }
    ],
    "view"
  >;

  confirmAttendance: TypedContractMethod<[ens: string], [void], "nonpayable">;

  eventMetadataURI: TypedContractMethod<[], [string], "view">;

  getCertificate: TypedContractMethod<
    [user: AddressLike],
    [
      [bigint, bigint, string] & {
        eventId: bigint;
        timestamp: bigint;
        ens: string;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  poap: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setEventMetadataURI: TypedContractMethod<
    [_uri: string],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "attended"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "certificates"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, string] & {
        eventId: bigint;
        timestamp: bigint;
        ens: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "confirmAttendance"
  ): TypedContractMethod<[ens: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "eventMetadataURI"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getCertificate"
  ): TypedContractMethod<
    [user: AddressLike],
    [
      [bigint, bigint, string] & {
        eventId: bigint;
        timestamp: bigint;
        ens: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "poap"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setEventMetadataURI"
  ): TypedContractMethod<[_uri: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "AttendanceConfirmed"
  ): TypedContractEvent<
    AttendanceConfirmedEvent.InputTuple,
    AttendanceConfirmedEvent.OutputTuple,
    AttendanceConfirmedEvent.OutputObject
  >;
  getEvent(
    key: "EventMetadataUpdated"
  ): TypedContractEvent<
    EventMetadataUpdatedEvent.InputTuple,
    EventMetadataUpdatedEvent.OutputTuple,
    EventMetadataUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "AttendanceConfirmed(address,string,uint256)": TypedContractEvent<
      AttendanceConfirmedEvent.InputTuple,
      AttendanceConfirmedEvent.OutputTuple,
      AttendanceConfirmedEvent.OutputObject
    >;
    AttendanceConfirmed: TypedContractEvent<
      AttendanceConfirmedEvent.InputTuple,
      AttendanceConfirmedEvent.OutputTuple,
      AttendanceConfirmedEvent.OutputObject
    >;

    "EventMetadataUpdated(string)": TypedContractEvent<
      EventMetadataUpdatedEvent.InputTuple,
      EventMetadataUpdatedEvent.OutputTuple,
      EventMetadataUpdatedEvent.OutputObject
    >;
    EventMetadataUpdated: TypedContractEvent<
      EventMetadataUpdatedEvent.InputTuple,
      EventMetadataUpdatedEvent.OutputTuple,
      EventMetadataUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
