/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IPOAP,
  IPOAPInterface,
} from "../../../contracts/EventManager.sol/IPOAP";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "attendee",
        type: "address",
      },
      {
        internalType: "string",
        name: "tokenURI",
        type: "string",
      },
    ],
    name: "mintPOAP",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IPOAP__factory {
  static readonly abi = _abi;
  static createInterface(): IPOAPInterface {
    return new Interface(_abi) as IPOAPInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IPOAP {
    return new Contract(address, _abi, runner) as unknown as IPOAP;
  }
}
